-- Utworzenie typów ENUM
CREATE TYPE shipped_status_enum AS ENUM ('UNSENT', 'SENT', 'DELIVERED');
CREATE TYPE return_status_enum AS ENUM ('IN_PROGRESS', 'PENDING', 'RESOLVED', 'FAILED_DELIVERY');

-- Tabela ORDERS
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    amount DECIMAL(10,2) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    shipped_status shipped_status_enum ,
    order_date DATE NOT NULL
);

-- Tabela TICKETS
CREATE TABLE tickets (
    thread_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT DEFAULT NULL REFERENCES orders(order_id) ON DELETE SET NULL,
    contact_email VARCHAR(255) DEFAULT NULL,
    return_status return_status_enum DEFAULT 'IN_PROGRESS',
    return_reason TEXT DEFAULT NULL,
    admin_note TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);